# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 */4 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: main
          user: MatteoGheza
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Rome
          plugin_habits: no
          #plugin_habits_days: 14
          #plugin_habits_facts: yes
          #plugin_habits_from: 200
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_lines: yes
          plugin_notable: yes
          plugin_traffic: yes
          plugin_topics: yes
          plugin_topics_mode: "mastered"
          plugin_wakatime: no
          #plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          #plugin_wakatime_days: 7
          #plugin_wakatime_sections: time, projects, projects-graphs
          #plugin_wakatime_limit: 4
